# Generated by Django 4.2.3 on 2023-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
