# Generated by Django 4.2.3 on 2023-07-14 13:47

from django.db import migrations, models
import django.db.models.deletion
import tgapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0002_user_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=1024)),
                ('image', models.ImageField(upload_to=tgapp.models.image_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgapp.user')),
            ],
        ),
    ]
