# Generated by Django 4.2.3 on 2023-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0003_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='user',
        ),
    ]
