# Generated by Django 4.2.3 on 2023-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0004_remove_mediafile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_login', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
