# Generated by Django 4.2.3 on 2023-07-14 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0005_channeldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 19, 12, 3, 487170)),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 19, 12, 3, 487170)),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tg_groups',
            field=models.ManyToManyField(related_name='telegram_groups', to='tgapp.channeldata'),
        ),
    ]
